name: client
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_analytics: ^12.0.1
  firebase_messaging: ^16.0.1
  firebase_storage: ^13.0.1
  google_sign_in: ^5.4.0

  # Utilities
  universal_html: ^2.0.10
  permission_handler: ^11.3.1
  url_launcher: ^6.1.10
  file_selector: ^1.0.3
  flutter_markdown: ^0.7.3+1
  cupertino_icons: ^1.0.8
  pinput: ^5.0.2
  image_picker: ^0.8.7+5
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.12
  http: ^1.1.0
  provider: ^6.1.5
  cached_network_image: ^3.4.1
  chewie: ^1.8.5
  video_player: ^2.8.1 
  path_provider: ^2.1.3 
  open_filex: ^4.3.2
  uuid: ^4.4.0
  dio: ^5.0.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.8.0
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/
